<a href="https://colab.research.google.com/github/m-mehabadi/grad-maker/blob/main/_notebooks/Testing_GradientMaker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

http://www.cs.cmu.edu/~pradeepr/convexopt/Lecture_Slides/dual-ascent.pdf

In [61]:
import numpy as np
# import torch
import matplotlib.pyplot as plt

In [88]:
# dim=2000000
# a = 100*np.random.randn(4, dim) + 1123
# g = np.random.randn(dim, 1)
# b = (a-np.mean(a, axis=1)[:, np.newaxis])/np.std(a, axis=1)[:, np.newaxis]
# np.mean(b@g/dim)

In [63]:
def gradient_maker(domain_grads, epsilon=0.5, alpha=0.01, eff=0.1):
    def log():
        print(f"Iter={iter}, Condition={np.min(dgr@g/dim)}")
    
    # def null(A, eps=1e-15):
    #     u, s, vh = np.linalg.svd(A)
    #     # print(vh)
    #     null_space = np.compress(s <= eps, vh, axis=0)
    #     return null_space.T

    def null(A):
        from scipy.linalg import null_space
        n = null_space(A, rcond=1)
        if n.shape[1] < 1:
            return False, None
        r = np.sqrt(np.sum((A@n)**2, axis=0)/n.shape[1])
        if np.min(r) >= 1e-2:
            return False, None
        return True, n.T[np.argmin(r)].reshape(-1, 1)
    
    def scale():
        G = np.concatenate((g.reshape(1, -1), domain_grads), axis=0)
        is_fine, n = null(G@G.T)
        if not is_fine:
            return np.mean(np.sqrt(np.sum(domain_grads**2, axis=1)))/np.sqrt(np.sum(g**2))
        n /= np.sum(n[1:])
        return -1.*n[0,0]

    dgr = np.copy(domain_grads)
    number_of_domains, dim = dgr.shape

    #
    dgr /= np.sqrt(np.sum(dgr**2, axis=1))[:, np.newaxis]
    
    #
    g = np.random.randn(dim)
    g /= np.sqrt(np.sum(g**2))
    u_ = np.zeros(number_of_domains)
    
    iter = 0
    while not np.min(dgr@g/dim) >= epsilon:

        log()
        
        u_ = u_ + alpha*((1.+eff)*epsilon - (dgr@g)/dim)
        g = (1./number_of_domains)*np.sum(((1+u_).reshape(number_of_domains, 1))*dgr, axis=0)

        iter += 1
    
    log()
    return scale()*g

### Testcases

Now let's write some test cases to make sure everything is working correctly


In [64]:
epsilon=10
alpha=0.9

In [70]:
grads = 0.0000001*np.random.randn(2, 3) - 10000000
print(grads)

[[-10000000.00000006 -10000000.00000006 -10000000.00000017]
 [-10000000.00000002  -9999999.99999993 -10000000.00000006]]


In [71]:
g = gradient_maker(grads, epsilon=epsilon, alpha=alpha)
print(g)

Iter=0, Condition=0.12624283122407595
Iter=1, Condition=3.5954604839661113
Iter=2, Condition=5.816822338776277
Iter=3, Condition=7.3717756371433945
Iter=4, Condition=8.460242946000376
Iter=5, Condition=9.222170062200265
Iter=6, Condition=9.755519043540184
Iter=7, Condition=10.128863330478131
[-10000000.00000009 -10000000.00000004 -10000000.00000017]
